mex mex_compute_core_freespace.cpp
mex mex_compute_core_freespace_unexplained.cpp
mex mex_dist_weighted_double.cpp
mex mex_door_cost.cpp
mex mex_feature2D.cpp
mex mex_FeatureVisibility2D.cpp
mex mex_fill_inner.cpp
mex mex_fill_inner_rectangle.cpp
mex mex_find_ceil_line.cpp
mex mex_find_side_line.cpp
mex mex_find_start_end.cpp
mex mex_findBoundary.cpp
mex mex_genFreeSpaceEvidence.cpp
mex mex_genPointEvidence.cpp
mex mex_genPointNormalEvidence.cpp
mex mex_normalize_feature.cpp
mex mex_shortest_path_reconstruction_normal.cpp
mex mex_vgFilter.cpp
mex mex_shortest_path.cpp
mex mex_ransac_manhattan_1st.cpp
mex mex_ransac_manhattan_2nd.cpp
mex mex_gdt.cpp
mex mex_plane_fitting_ransac.cpp -I"SPECIFYYOUREIGEN**Eigen3.2.2" % You need to install Eigen library ("http://eigen.tuxfamily.org/index.php?title=Main_Page") and put the installation path here
